### ISSUE TITLE
Fails if the file path contains spaces

### ISSUE THREAD

**Issue by hutattedonmyarm** [iansan5653/vscode-format-python-docstrings#11]
Might need to wrap the file path in quotes when calling docstring

**Comment by iansan5653** [comment]
Sorry I've been offline dealing with Hurricane Dorian. Thanks for filing this, I'll definitely check that out.

**Comment by hutattedonmyarm** [comment]
No worries, hope you’re safe!

**Comment by iansan5653** [comment]
Thanks so much for reporting this significant issue! It should be fixed in version 1.1.0. Would you please try it out and confirm that it works now?

**Comment by hutattedonmyarm** [comment]
Thanks, works now
