### ISSUE TITLE
error

### ISSUE THREAD

**Issue by erickyaniz** [iansan5653/vscode-format-python-docstrings#13]
Could not format docstrings.

**Comment by iansan5653** [comment]
Hello, thanks for submitting an issue! Unfortunately I cannot help without more information. Can you give me your system information (extension version, VSCode version, and operating system) and describe what you were doing when encountering this error? Has the command ever run successfully or does it always raise this error? If it only happens with a specific file, it would be great if you could share that file if possible.

**Comment by iansan5653** [comment]
Good afternoon @erickyaniz. I still don't have any info on your error so there's not much I can do right now, however it's possible that it may be fixed with the latest release. Could you try updating and let me know how it works?

**Comment by iansan5653** [comment]
Closing for now due to lack of information. Feel free to comment and I'll reopen it.
