### ISSUE TITLE
Trouble installing/using

### ISSUE THREAD

**Issue by LightCC** [iansan5653/vscode-format-python-docstrings#17]
The instructions on the extension say:

> To set the default formatter that is run when you run the Format Document, on Python files, add the following to your settings.json:
> 
> "[python]": {
>     "editor.defaultFormatter": "iansan5653.format-python-docstrings"
> }

but where is this settings.json?  I can't figure out how to set this in the base user settings file - it creates an error if you paste it in there. (there is a single {} block and this can't be nested or create a new one with this text.

Has the format of settings changed?

Am I missing something simple here?

**Comment by iansan5653** [comment]
@LightCC You do need to place it inside the curly braces, like so:
```json
{
    "[python]": {
      "editor.defaultFormatter": "iansan5653.format-python-docstrings"
    },
}
```
Let me know if this doesn't work.
