### ISSUE TITLE
Relative paths and VSCode predefined variables don't work for python.pythonPath

### ISSUE THREAD

**Issue by willfrey** [iansan5653/vscode-format-python-docstrings#36]
I often have my virtualenv in my project's root directory, usually in `.venv`. I also like to leave off the hard-coded prefix, so my python path is often just 

```json
{
  "python.pythonPath": ".venv/bin/python"
}
```

This extension, however, doesn't seem to like this.

The extension also doesn't seem to like the predefined VSCode variables [mentioned here](https://code.visualstudio.com/docs/editor/variables-reference). For example, I could also have written

```json
{
  "python.pythonPath": "${workspaceFolder}/.venv/bin/python"
}
```

It'd be nice if the extension handled these cases!

Thanks for your work!

**Comment by iansan5653** [comment]
Thanks for the report! I hadn't considered those - I'll look into this and should have it fixed this weekend.

**Comment by willfrey** [comment]
Thanks for the quick response!

**Comment by iansan5653** [comment]
Sorry for the delay - I'm close to releasing a fix but I still need to resolve one more failing test first.

**Comment by iansan5653** [comment]
Thanks again for reporting this - if you could please update to the latest version (`1.2.1`) and try it again, I'd really appreciate it.

**Comment by willfrey** [comment]
It works for both cases! Thank you for fixing this!

**Comment by iansan5653** [comment]
I'm glad to hear that, thanks for checking!
