### ISSUE TITLE
Plugin fails when Python 3 and 2 are installed

### ISSUE THREAD

**Issue by TheDiveO** [iansan5653/vscode-format-python-docstrings#40]
With Python2 now EOL in January 2020 shouldn't this plugin be not only compatible with Python3 but also (optionally?) using it?

**Comment by iansan5653** [comment]
I'm not sure what you mean -- the plugin is not tested at all with Python 2 - I only intend to support 3+. Can you describe what error you're seeing and how your environment is set up?

**Comment by TheDiveO** [comment]
Base system is Ubuntu 19.04 "disco".
- `sudo pip3 install docformatter` installs docformatter-1.3.1
- Python Docstring Formatter plugin 1.2.0
- vsc 1.40.2

Next, Ctrl-Shift-P, "Format Document with...", then "Python Docstring Formatter". This results in two error message boxes appearing:

```
Command failed: python -m docformatter "/home/.../xxx.py" --wrap-summaries 79 --wrap-descriptions 72
/usr/bin/python: No module named docformatter
```

...shouldn't this be `python3`, not `python`? In vsc, I've currently selected "Python 3.7.3 64-bit".

The other error message is saying that Python module docformatter isn't installed. Clicking on "install" then yields:

```
Could not install docformatter automatically. Make sure that pip is installed correctly and try manually installing with 'pip install --upgrade docformatter. 

 Full error: Error: Command failed: python -m pip install --upgrade docformatter
/usr/bin/python: No module named pip
'.
```

Again, this shouldn't run `python` but `python3`, should it?

Repeating the whole procedure again yields the same errors again. On the basis of these error messages only trying to call `python` but not `python3` I opened this issue.

**Comment by TheDiveO** [comment]
I notice that I need to change the title, because I have python2 also installed.

**Comment by iansan5653** [comment]
Thank you for the detailed info! You're right, this is a bug - if you have Python 3 selected in VSCode then it should run 3 without a problem, so that's definitely something I need to look into. 

If it doesn't find that setting, it defaults to `python` or `py` by running `python --version` as a test command to see what works. It should probably check what version is actually output rather than just whether the test command succeeds or fails, and I can also add `python3` to the list of possibilities.

**Comment by iansan5653** [comment]
Thanks again for reporting this - if you could please update to the latest version (`1.2.1`) and try it again, I'd really appreciate it.

**Comment by TheDiveO** [comment]
Yes, 1.2.1 now works, thank you very much!

With my default values I first get this helpful error message which allowed me to set the settings accordingly.

```
The Python path set in the "python.pythonPath" setting is invalid or points to Python 2. Check the value or clear the setting to use the global Python installation. The extension is not compatible with Python 2.
```

And in fact, the value of "Python: Python Path" in settings defaults to "python", not "python3".

**Comment by iansan5653** [comment]
👍 Glad to hear it worked for you!
